curve:
  import:
  columns_old:
    - Date (YYYY-MM-DD as UTC)
    - Merchant
    - Txn Amount (Funding Card)
    - Card Name
    - Category
  columns_new:
    - Day
    - Expense_name
    - Amount
    - Bank
    - Comment
  Day: "%Y-%m-%d"
ing:
  import:
    sep: ";"
  columns_old:
    - Date
    - Bénéficiaire
    - Montant
    - Bank
    - Communication
  columns_new:
    - Day
    - Expense_name
    - Amount
    - Bank
    - Comment
  Remove:
    - Giampaolo Casolla
  Day: "%d/%m/%Y"
n26:
  import:
  columns_old:
    - Booking Date
    - Partner Name
    - Amount (EUR)
    - Bank
    - Payment Reference
  columns_new:
    - Day
    - Expense_name
    - Amount
    - Bank
    - Comment
  Day: "%Y-%m-%d"
revolut:
  import:
  columns_old:
    - Started Date
    - Description
    - Amount
    - Bank
    - Type
  columns_new:
    - Day
    - Expense_name
    - Amount
    - Bank
    - Comment
  Remove:
    - To EUR
    - Payment from Giampaolo Casolla
  Day: "%Y-%m-%d %H:%M:%S"
