name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Setup test environment
        run: |
          # Create a temporary .env file with placeholder values for testing
          echo "OPENAI_API_KEY=dummy-key-for-testing" > .env

      - name: Check code formatting with Black
        run: uv run black --check .

      - name: Lint with flake8
        run: uv run flake8 .

      - name: Check imports with isort
        run: uv run isort --check .

      - name: Type check with mypy
        run: uv run mypy .

      - name: Run tests with pytest
        run: uv run pytest --cov=import_bank_details --cov-report=xml --cov-fail-under=80

      - name: Generate coverage report
        run: uv run pytest --cov=import_bank_details --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: giampaolocasolla/import-bank-details
          files: ./coverage.xml
          fail_ci_if_error: false
